/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "blog-app-20191206223226-hostingbucket-blogapp",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://blog-app-20191206223226-hostingbucket-blogapp.s3-website.us-east-2.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-2:7addcbfa-002a-4c8f-aeb3-d02138502a27",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_8B3Cfvc9M",
    "aws_user_pools_web_client_id": "36a9q3q8k5r7is2eq74uor7a1n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://dlv32jimsngyrhtbfinn3logku.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
